CREATE TABLE BOOK (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50),
    AUTHOR VARCHAR(50),
    ISBN VARCHAR(13)
 );

CREATE TABLE CUSTOMER (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(25),
    SURNAME VARCHAR(25),
    ADDRESS VARCHAR(75),
    PHONE VARCHAR(50)
 );

CREATE TABLE BORROW (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    BOOK-ID BIGINT NOT NULL
    CUSTOMER_ID BIGINT NOT NULL
    BORROW_DATE DATETIME,
    RETURN_DATE DATETIME,
    RETURNED BOOLEAN,
    FOREIGN KEY(BOOK_ID)
        REFERENCES BOOK(ID),
    FOREIGN KEY(CUSTOMER_ID)
        REFERENCES CUSTOMER(ID)
 );


